# Use a Node.js LTS image as the base image for the frontend
FROM node:18-alpine

WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the rest of the frontend application code to the container
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]