services:
#backend:
#  build:
#    dockerfile: Dockerfile.dev
#    context: ./backend
#  ports:
#    - "8080:8080"
#  depends_on:
#    - db
#  volumes:
#    - ./backend/assets:/app/assets#
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./frontend/:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mdDatabase
      POSTGRES_USER: mdAdmin
      POSTGRES_PASSWORD: 1337asdf
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

volumes:
  postgres-data:


