[package]
name = "markdown-blog-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "4"
postgres = "0.19.5"
serde = { version ="1", features = ["derive"] }
tokio = "1.29.1"
tokio-postgres = "0.7.8"

